var once=0;
function P_adventures(b,d){$(".tro").remove();once++;if(1<once)return!1;$("#func2").val(d);""==b&&(b=pm);$(".zv").remove();for(var a=b.getElementsByTagName("Model"),e=$(".cont"),f="",l=0,c=0;c<a.length;c++){model_type=a[c].getAttribute("model_type");maker_group=a[c].getAttribute("maker_group");model_fil=a[c].getAttribute("model_fil");d.match(/\-group$/);var h=!1,g="";model_img=a[c].getAttribute("model_img");""==model_img&&(model_img="cover.jpg");model_desc=a[c].getAttribute("model_desc");textValue=
a[c].firstChild.nodeValue;textValue=textValue.replace(/\\"/g,'"').replace(/\\'/g,"'");model_desc=a[c].getElementsByTagName("desc")[0].firstChild.nodeValue;model_desc=model_desc.replace(/\\"/g,'"').replace(/\\'/g,"'");model_img=a[c].getElementsByTagName("fimg")[0].firstChild.nodeValue;"#"==model_img&&(model_img="over.jpg");model_link=a[c].getElementsByTagName("o")[0].firstChild.nodeValue;model_group=a[c].getAttribute("model_group");site="."+model_link;fetchcnt="c"==model_type?$(site).html():"";""!=
d?(eval("var urlStringer = /"+d+"/;"),model_fil.match(urlStringer)==d&&(0==l&&(f=a[c].getElementsByTagName("grv")[0].firstChild.nodeValue,g=a[c].getElementsByTagName("intro")[0].firstChild.nodeValue),h=!0,l++)):"c"==model_type&&""!=$("#f_make").val()&&""==$("#f_model").val()&&$("#f_make").val()==maker_group?h=!0:"c"==model_type&&""==$("#f_make").val()&&""==$("#f_model").val()?h=!0:"c"==model_type&&$("#f_make").val()==maker_group?h=!0:"c"==model_type&&""==$("#f_make").val()&&(h=!0);var k="c"==model_type&&
""!=d?" style='display:none' ":"";1==h&&("-"==f?$(".ei-slider-large").html('<li><img src="../c/large/www-collage-adventures.jpg" alt=""/><div class="ei-title"></div></li>'):""!=f&&$(".ei-slider-large").html('<li><img src="../c/large/'+f+'" alt=""/><div class="ei-title"></div></li>'),"-"!=g&&1==l&&(g=g.replace(/bbbb/g,"<b>"),g=g.replace(/qqqq/g,"</b>"),g=g.replace(/brbr/g,"<br />"),$('<p class="tro">'+g+"</p>").appendTo(e)),"c"==model_type?$("<div "+k+' class="eight columns zv '+maker_group+'"><h2><a href="javascript:k1(\''+
model_link+"');selectByValue('"+model_link+"');$(window).scrollTop(0);\">"+textValue+" <span>"+fetchcnt+'</span></a></h2><img src="../c/adventures/'+model_img+'" class="lar" alt="'+textValue+'" /><div class="pp"><p class="kan">'+model_desc+'</p><div class="v"><a href="javascript:k1(\''+model_link+"');selectByValue('"+model_link+'\');$(window).scrollTop(0);"><img src="../c/view.png"></a></div><div class="clear"></div></div></div>').appendTo(e):"poiu"==model_fil.match(/poiu/)?$("<div "+k+' class="eight columns zv '+
maker_group+'"><h2><a href="javascript:once = 0;P_adventures(pm,"dvfc");">'+textValue+" <span>"+fetchcnt+'</span></a></h2><img src="../c/adventures/'+model_img+'" class="lar" alt="'+textValue+'" /><div class="pp"><p class="kan">'+model_desc+'</p><div class="v"><a href="javascript:once = 0;P_adventures(pm,\'dvfc\');"><img src="../c/view.png"></a></div><div class="clear"></div></div></div>').appendTo(e):$("<div "+k+' class="eight columns zv '+maker_group+'"><h2><a href="../'+model_link+'">'+textValue+
" <span>"+fetchcnt+'</span></a></h2><img src="../c/adventures/'+model_img+'" class="lar" alt="'+textValue+'" /><div class="pp"><p class="kan">'+model_desc+'</p><div class="v"><a href="../'+model_link+'"><img src="../c/view.png"></a></div><div class="clear"></div></div></div>').appendTo(e));""==d&&$(".ei-slider-large").html('<li><img src="../c/large/www-adventures-tunku-abdul-rahman-park-under-water.jpg" alt=""/><div class="ei-title"></div></li>')}""==$("#func2").val()&&$("<div "+k+' class="eight columns zv"><h2><a href="../custom-trips">Custom Trips</a></h2><img src="../c/adventures/custom-trips.jpg" class="lar" alt="" /><div class="pp"><p class="kan">Our forte is custom-made itineraries based on clients\' specific interests and travel\u00adstyle, and all clients are assigned a travel consultant who will correspond with client on building the itinerary...</p><div class="v"><a href="../custom-trips"><img src="../c/view.png"></a></div><div class="clear"></div></div></div>').appendTo(e);
"dvfc"==$("#func2").val()?$("<div "+k+' class="eight columns zv '+maker_group+'"><h2>&nbsp;</h2><a href="javascript:clean_ell();once = 0;P_adventures(\'\',\'danum-valley\');"><img src="../c/adventures/back.jpg" class="lar" alt="" /></a><div class="pp"><p class="kan"></p><div class="v"></div><div class="clear"></div></div></div>').appendTo(e):""!=$("#func2").val()&&$("<div "+k+' class="eight columns zv '+maker_group+'"><h2>&nbsp;</h2><a href="javascript:clean_ell();once = 0;P_adventures(\'\',\'\');document.getElementById(\'f_model\').options[0].selected = true;"><img src="../c/adventures/back.jpg" class="lar" alt="" /></a><div class="pp"><p class="kan"></p><div class="v"></div><div class="clear"></div></div></div>').appendTo(e)}
function k1(b){$("#k1").val(b)}
function P_model(b){for(var d=document.getElementById("f_model"),a=d.options.length-1;-1<a;a--)d.options[a]=null;b=b.getElementsByTagName("Model");var e=$("#f_make").val(),f,a=document.getElementById("f_make"),l=a.options[a.selectedIndex].value,c;c=1;f=new Option("All "+e,"",!1,!1);d.options[0]=f;for(a=0;a<b.length;a++)f=!1,maker_group=b[a].getAttribute("maker_group"),model_type=b[a].getAttribute("model_type"),textValue=b[a].firstChild.nodeValue,model_link=b[a].getElementsByTagName("o")[0].firstChild.nodeValue,model_desc=
b[a].getElementsByTagName("desc")[0].firstChild.nodeValue,model_img=b[a].getElementsByTagName("fimg")[0].firstChild.nodeValue,""==e?"c"==model_type&&(f=!0):maker_group==l&&"c"==model_type&&(f=!0),1==f&&(f=new Option(textValue,model_link,!1,!1),d.options[c]=f,c+=1);selectByValue($("#func2").val())}function selectByValue(b){val=b;for(var d=document.getElementById("f_model"),a=0;a<d.options.length;a++){var e=d.options[a];e.value==b&&(e.selected=!0,once=0,P_adventures("",b))}}
function clean_ell(){document.getElementById("func3").value="";document.getElementById("f_browse").options[0].selected=!0};